### ISSUE TITLE
Remove pdftools dependency

### ISSUE THREAD

**Issue by jhelvy** [jhelvy/renderthis#13]
The following line inside `build_pdf_complex()` is the only time the pdftools library is used:

`pdftools::pdf_combine(pdf_files, output = output_file)`

There's probably a way to combine pdf files with `pagedown::chrome_print()` or something else that is already widely used in the package.

**Comment by gadenbuie** [comment]
FYI the complicated bit about complex slides is that you can't rely on the print styles or count on there being only one "view" per slide. 

Using panelset, for example, adds "virtual slides" within each slide — okay so really it doesn't, it hijacks the next slide events and changes the panel instead of the slide — so we couldn't print the whole deck at once. 

Instead, we have to print slide by slide, using the virtual <kbd>&rarr;</kbd> to advance the slides. In the end, we get a stack of PDF files that need to be combined somehow, and pdftools was the easiest I found.
