### ISSUE TITLE
Input and output name mismatches cause errors in output chains

### ISSUE THREAD

**Issue by gadenbuie** [jhelvy/renderthis#28]
If the requested output file name sans extension doesn't match the input file name without the extension, errors can arise when intermediate formats need to be generated.

``` r
library(xaringanBuilder)
build_png(
    input = "https://jhelvy.github.io/xaringanBuilder/reference/figures/slides.html", 
    output_file = "test.png"
)
#> ℹ Building test.pdf from slides.html
#> ✓ Building test.pdf from slides.html ... done
#> 
#> ℹ Building test.png from slides.pdf
#> Error in normalizePath(pdf, mustWork = TRUE): path[1]="/private/var/folders/zw/8z2vpz1s0cl3gwpyh5p72mwh0000gn/T/Rtmp3nVWkK/reprex-2a9162281673-deep-polyp/slides.pdf": No such file or directory
```

Here `build_png()` uses `slides.html` to build `test.pdf` (since we are going wanting to generate `test.png`), but later looks for `slides.pdf` when converting from PDF to png.

**Comment by jhelvy** [comment]
Yup, this is definitely an issue. Right now all the paths get created with the (non-exported) `build_paths()` function early in the build process. But those paths aren't updated for intermediate formats, so I think the fix is simply to call `build_paths()` again to update all the paths any time an intermediate format gets built. I'll see if I can fix this.
