### ISSUE TITLE
Failed to generate PDF output, image returns HTTP status code 404

### ISSUE THREAD

**Issue by koliajaykr** [jhelvy/renderthis#42]
after using `build_pdf()` function RStudio console is show this error:

Error in force(expr) : 
  Failed to generate output. Reason: Failed to open http://127.0.0.1:5262/Volumes/Macintosh%20HD%20-%20Data/2019-07-06-manhole/slides_files/figure-html/auth1-img-1.png (HTTP status code: 404)

**Comment by gadenbuie** [comment]
The problem occurs because you have either referenced a file on your computer that isn't in the same directory as your slides or you have called a function that turns a relative path to the `auth1-img-1.png` image into an absolute path.

Please take a look at the comment here https://github.com/jhelvy/xaringanBuilder/issues/40#issuecomment-970408221 and see if that helps clarify and resolve the issue.

If not, please provide a [reprex (a small, reproducible example)](https://reprex.tidyverse.org/articles/articles/learn-reprex.html) that recreates your problem and will help us to debug the issue.

**Comment by koliajaykr** [comment]
Thank you so much Garrick for your prompt help. This issue is resolved now.

Adding `self_contained: true` in the YAML worked. And, I really liked your suggestion to include CSS codes to make sure all figures are within the margin while printing pdf.

**Comment by gadenbuie** [comment]
Glad to hear that helped and that your issue was resolved! Happy presenting!

**Comment by jhelvy** [comment]
Shout out to @gadenbuie just crushing issues day before Thanksgiving - 2 in one day!
